workflows:
  flutter-release:
    name: Flutter iOS + Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter analyze
      - flutter test
      - flutter build apk --release
      - flutter build ios --release --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.ipa
    publishing:
      email:
        recipients:
          - you@example.com
